### ISSUE TITLE
Chord pro format convert to sheet text

### ISSUE THREAD

**Issue by AhLee7638** [menees/Chords#1]
Hi
Thanks for this great lib. May i know how to convert the chordpro format to chords over text type ? 
i try but seem can't. please advise
Thanks

**Comment by menees** [comment]
You're welcome, and I'm glad you like it!

It was on my list to add this functionality, so I've started working on it tonight. In 0.8.3-beta, I've added a `ChordProLyricLine.Split()` method to convert a single ChordProLyricLne into "chords over text" by return a ChordLine and a LyricLine with correct indentation. I've added unit tests for it too, so you can see an example usage.

If I have time soon, I'd also like to add a ChordsOverTextTransformer class to easily transform an entire Document into chords over text format. And then I'd like to add options to the Blazor app to convert from ChordPro format into chords over text format. When I do that I'll probably change all the DocumentTransformer classes to implement an abstract Transform method instead of each having their own custom named method (e.g., ToChordPro). Since the library is still in beta, I'm still working on the final API. I hope the changes won't impact your usage too much.

**Comment by AhLee7638** [comment]
Hi, Thanks for the advise, i will take a look the ChordProLyricLine function.
ya,the ChordsOverTextTransformer function will helpful with me.but just take your time,dont be rush.

Thank you

**Comment by menees** [comment]
Release [0.8.5-beta](https://github.com/menees/Chords/releases/tag/v0.8.5-beta) has a new ChordOverLyricTransformer. The CLI app and the web app ([chords.menees.com](https://chords.menees.com/)) also support converting to "chords over text" format.

**Comment by AhLee7638** [comment]
Thank you very much !! This helpful for me !!
Just now i tested and aware 1 issues for convertion, if the text is not a engilsh (like jp cn etc..),the chord over text result will not accurately.
example 
今日[G#5]何食べた？　好[G#5]きな本は？　遊(あ[EM7]そ)びに行くならど[D#]こに行くの？
convert result
G#5    G#5      EM7      D#
今日何食べた？　好きな本は？　遊(あそ)びに行くならどこに行くの？

i think is the font problem ? do you have any idea ?
Sorry disturb you again..

**Comment by menees** [comment]
It's designed to work with a monospaced font (i.e., where every character is rendered with the same width). The whitespace used between the chords in the ChordLine are separated assuming that each character in the LyricLine below it will be rendered in the same width.

So, a ChordPro line like `[C] Oh, [Am]thinkin' about our youn[G]ger years` will render as:
![image](https://github.com/menees/Chords/assets/13545825/82c24127-2391-4303-b11b-a27cfdb20e54)

However, your example looks like this:
![image](https://github.com/menees/Chords/assets/13545825/d1f25a96-853e-4e1d-9350-7066d7abc373)

The rendering in the browser's TextArea is using wider characters for the Kanji (?) characters like '今' than for the English characters like 'G' and punctuation like '?'. I don't know much about when a monospace font uses non-monospaced characters. There may be a "wider space" Unicode character that you can replace the standard spaces with in your own rendering. For example, see [Regular and Unusual Space Characters](https://unicode-explorer.com/articles/space-characters).

The point is that ChordProLyricLine.Split() is just giving back ChordLine and LyricLine instances where the character counts are in sync. If some characters are rendered wider than others, then you'll have to account for that in your rendering.

**Comment by AhLee7638** [comment]
I see,i have notice that will include many spacing in 1 characters,and this is depend on the font used.
I will try to do something in my rendering part,I think shouldn't be difficult.

Thank you for advise 👍
